### ISSUE TITLE
Invalid CSV file handling

### ISSUE THREAD

**Issue by mudrd8mz** [GopalSharma/moodle-qformat_csv#1]
If the CSV file does not have the expected structure, the plugin should inform the user in a nice way. Currently, multiple PHP notices are raised (Moodle has zero tolerance policy on notices and warnings) and the plugin dies because it tries to insert a record into the database with empty questiontext.

![image](https://user-images.githubusercontent.com/85831/44560952-824c5e80-a752-11e8-9fc8-ccf78536fb95.png)

![image](https://user-images.githubusercontent.com/85831/44560966-8d9f8a00-a752-11e8-9374-fada959bfd9f.png)

**Comment by GopalSharma** [comment]
I have tried many files with various structure but could not replicate the error which you have shared.
Is it possible for you to share all the CSV files, using which you are getting the error?
You can email me all the files with the various structure which causing the **PHP notices and warnings**
Following are the setting done by me in **Site administration** -> **Development** -> **Debugging**
**Debug messages :DEVELOPER: extra Moodle debug messages for developers
Display debug messages : yes**

I'm getting the the following error when question text and few option are completly erased from the CSV file.
![error_importing](https://user-images.githubusercontent.com/1146458/44728977-61da2680-aafb-11e8-9bc8-99ed41f6caae.png)

Following error I get when I remove the Answer Field from the **Header** like removing 'Answer 1' and 'Anwser 2'
![error_importing_2](https://user-images.githubusercontent.com/1146458/44728976-61da2680-aafb-11e8-8804-e01952cd8bc4.png)

Above errors are acepatable, right?
Please share the CSV files which are causing the  **PHP notices and warnings**
Thank you

**Comment by mudrd8mz** [comment]
If I recall correctly, I got it when trying to import some non-CSV file. In either case, errors like this should be better communicated with the user.
