### ISSUE TITLE
Images in Question or Answer Choice

### ISSUE THREAD

**Issue by upliftk12** [GopalSharma/moodle-qformat_csv#10]
First off, thank you for your contribution. This is a great plugin.  I am wondering if there is any capability for adding the URL of images or HTML code in the import?

**Comment by GopalSharma** [comment]
@upliftk12 , Thank you for your appreciation. This a nice suggestion, I will have a look at it.

**Comment by tharindus1992** [comment]
Dear Sir, thank you for your plugin. This is an awesome plugin. I am wondering the same as @upliftk12.....

**Comment by tharindus1992** [comment]
How can I change this to upload HTML tags?

**Comment by GopalSharma** [comment]
@tharindus1992 
You would be able to add an HTML tag now, just make sure everything is within one line and there is no new line char added.
So, each line would be having a single question and answer data only.
![screenshot-newtab-2021 10 01-16_50_23](https://user-images.githubusercontent.com/1146458/135611926-47c0acef-d156-4204-aa2b-12f8b6127d21.png)
 Not tested with the image but you can test that as well. where the image would be in binary, like 
` <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU"/>`

**Comment by tharindus1992** [comment]
Dear @GopalSharma Sir,
Thank You for the update. Really appreciate your effort and taking the time to do the update to a small request made by us. I'll test this and let you know what happens. Again, Thank you so much dear @GopalSharma.
