### ISSUE TITLE
no feedback in export file, no column headers

### ISSUE THREAD

**Issue by englishwebtls** [GopalSharma/moodle-qformat_csv#11]
Hello
I'm using Moodle3.9.3
When I export quiz questions there is no feedback (neither general nor question specific) and no column headers in the export file.

Is this a bug?

**Comment by GopalSharma** [comment]
@englishwebtls 
 This isn't a bug.

**Comment by englishwebtls** [comment]
but your extended sample shows headers and feedback. What am I doing wrong? I followed your export instructions to the letter.

questionname | questiontext | A | B | C | D | Answer 1 | Answer 2 | answernumbering | correctfeedback | partiallycorrectfeedback | incorrectfeedback | defaultmark
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Question1 | The dmesg command | Shows user login logoff attempts | Shows the syslog file for info messages | kernel log messages | Shows the daemon log messages | C |   | 123 | Your answer is correct. | Your answer is partially correct. | Your answer is incorrect. | 1

**Comment by GopalSharma** [comment]
yes, but **extended** sample works only for importing  question into Moodle.
