### ISSUE TITLE
Make it clear that only multichoice questions are supported now

### ISSUE THREAD

**Issue by mudrd8mz** [GopalSharma/moodle-qformat_csv#2]
Please update the description at the plugins directory and make it clear that only multichoice questions are supported now.

**Comment by GopalSharma** [comment]
Thank you so much for reviewing this plugin David, I appreciate your time on reviewing this plugin.
I have updated the description as indicated by you.

**Comment by GopalSharma** [comment]
Please close the issue if you okay with the updated description.
Please update this issues here as well [](https://tracker.moodle.org/browse/CONTRIB-7392)
Much Thanks
