### ISSUE TITLE
Clarify the behaviour of the Answer 1 and Answer 2 fields

### ISSUE THREAD

**Issue by mudrd8mz** [GopalSharma/moodle-qformat_csv#3]
It is not clear what these fields are for, if both are supposed to hold a right answer, why there are only two etc.

**Comment by GopalSharma** [comment]
As of now, there can only one right answer or a maximum of two right answers. That is the reason it has only two fields as "Answer 1" and "Answer 2". "Answer 2" field is optional, if there is no value in that('Answer 2') field, then the question is imported as a single right answer having 100% grade for choosing it.
If there is value in the 'Answer 2 ' field weather(A or B or C or D) then each of the two answers has 50% of the grade of choosing each right answer, If a user selects both the right answer while answering, he gets the 100% ( 50 + 50 ) grade. If the user selects one right answer then the user gets 50% grade.
I will be adding the other fields(all four) for answers in future updates.
Please let me know if you still have any doubts about it.
![csv_ans](https://user-images.githubusercontent.com/1146458/44574637-99696b80-a7a7-11e8-8697-5c252fb72afa.png)

**Comment by mudrd8mz** [comment]
You might want to have a look at https://github.com/vinod4/My-Repository/tree/master/csvformat and get in touch with Vinod Kumar (@vinod4 here at github, https://moodle.org/user/profile.php?id=1564749 at moodle.org). They co-incidentally submitted yet another CSV import plugin that has some interesting design features. Please refer to https://tracker.moodle.org/browse/CONTRIB-7392 where I suggest you two to co-operate instead of compete on a very same plugin.

I think the other plugin was a bit more robust in terms of multiple answers.

**Comment by GopalSharma** [comment]
I have contacted **@Vinod** and not received any response from him yet. We have developed different plugins which seems to be similar.
Plugin which I have developed, if you can see, there so many options which could be added in the near future, like **feedback**(for all correct, incorrect and partials feedbacks), **question numbering**, **answernumbering**, **hidden** and so on.
**I tried to make the plugin as simple as possible for the end users to use it.**
With this plugin, a question can have two, three or four options, all work just fine.
If a user just wants two option then he can leave blank the other two option to keep the question option to just two with one answer and so on.
If you are clear about the **answer field** then please go ahead and close this issue.
