### ISSUE TITLE
Some modifes to support truefalse format,can I pull it?

### ISSUE THREAD

**Issue by hunterhqm** [GopalSharma/moodle-qformat_csv#8]
Hi，dear GopalSharma,I make some changes,now ,it's supported truefalse and multichoice. 
https://github.com/hunterhqm/Question-CSV-format

**Comment by hunterhqm** [comment]
now,it support multichoice,shortanswer,and truefalse

**Comment by GopalSharma** [comment]
You have already pulled it @hunterhqm, but I'm planning created separate plugin for this purpose, not to complicate the things for the users.
Your comment here will help those people, who want to use this, but this is not really an issue so request you to close it.

**Comment by hunterhqm** [comment]
I'm a beginner at GitHub,how to put the plugin on the moodle site?
@GopalSharma  By the way, what are the details of your new plan?
